import{i as l,S as d}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const f="52933898-64c235b98ac290495c49a4d77",p="https://pixabay.com/api/";async function m(t){const o=new URLSearchParams({key:f,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:20}),s=`${p}?${o}`,n=await fetch(s);if(!n.ok)throw new Error(`HTTP error: ${n.status}`);return(await n.json()).hits}function y(t){return t.map(({webformatURL:o,largeImageURL:s,tags:n,likes:e,views:r,comments:a,downloads:u})=>`
      <li class="card">
        <a href="${s}" target="_blank" rel="noopener noreferrer">
          <img src="${o}" alt="${n}" loading="lazy" />
        </a>
        <div class="stats">
          <div><span>Likes</span>${e}</div>
          <div><span>Views</span>${r}</div>
          <div><span>Comments</span>${a}</div>
          <div><span>Downloads</span>${u}</div>
        </div>
      </li>`).join("")}function g(){document.querySelector(".gallery").innerHTML=""}function h(t){document.querySelector(".gallery").innerHTML=t}const v=t=>l.show({class:"custom-error-toast",timeout:4e3,close:!0,overlay:!1,position:"topRight",title:"",message:t,progressBar:!1,transitionIn:"fadeInDown",transitionOut:"fadeOutUp",closeOnClick:!0}),c=t=>l.show({class:"custom-info-toast",timeout:3e3,close:!0,overlay:!1,position:"topRight",title:"",message:t,progressBar:!1,transitionIn:"fadeInDown",transitionOut:"fadeOutUp",closeOnClick:!0}),w=document.querySelector(".form"),i=document.querySelector(".loader");document.querySelector(".gallery");let L=new d(".gallery a",{captionsData:"alt",captionDelay:250});w.addEventListener("submit",O);async function O(t){t.preventDefault();const o=t.target.elements.search.value.trim();if(!o){c("Please, enter a search query!");return}g(),i.style.display="block";try{const s=await m(o);if(s.length===0){i.style.display="none",c("Sorry, there are no images matching your search query. Please try again!");return}const n=y(s);h(n),L.refresh()}catch(s){console.error(s),v("An error occurred while fetching images.")}finally{i.style.display="none"}}
//# sourceMappingURL=index.js.map
